# Generated by Django 5.2.15 on 2026-06-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Dine in', 'Dine in'), ('Take', 'Take')], max_length=20),
        ),
    ]
